### ISSUE TITLE
Systemd not starting - Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [geerlingguy/docker-ubuntu2004-ansible#18]
Hi everyone, I'm trying to test a role that installs postgresql using the docker driver for molecule but it seems that systemd is not starting. 

### Symptoms
- After postgres installation I get this [log](https://drive.google.com/file/d/1NnrzaZe_b8aJjehBPa80146X-LdPlOis/view?usp=sharing)
- Systemctl commands do not connect to bus
```
root@ubuntu2004:/# systemctl show
Failed to connect to bus: No such file or directory
root@ubuntu2004:/# systemctl status
Failed to connect to bus: No such file or directory
root@ubuntu2004:/# systemctl status postgresql
Failed to connect to bus: No such file or directory
```
(this container has been created using `molecule create && molecule login`)

### Molecule configuration
```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .

```

### My setup
- `ansible`: 2.11.3
- `molecule`: 3.4.0
- `molecule-docker`: 0.2.4
- `python`: 3.9
- `docker`: 20.10.8

**Comment by maxhoesel** [comment]
Fyi, this is an issue between Docker and newer systemd versions (248 and up): https://github.com/systemd/systemd/issues/19245.

One possible workaround is to boot with the kernel parameter `systemd.unified_cgroup_hierarchy=0`

**Comment by FedericoAntoniazzi** [comment]
Thank you for pointing this out, I wouldn't have thought the problem was systemd.

**Comment by LorenzoBettini** [comment]
I'm experiencing this problem as well in Ubuntu 21.10 where systemd is version 248...
I was wondering whether this might be an alternative solution https://github.com/gdraheim/docker-systemctl-replacement

**Comment by goshdarnitnick** [comment]
I had a similar issue on MacOS with Docker Desktop (which recently moved to cgroup v2). The only solution I found was to install a [beta build](https://github.com/docker/for-mac/issues/6073) mentioned in a github issue and revert back to cgroup v1.

**Comment by thom-vend** [comment]
If you are using docker for mac workaround can be to go back on cgroup v1
```bash
# Stop running Docker
test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'
# Install jq and moreutils so we can merge into the existing json file
brew install jq moreutils
# Add the needed cgroup config to docker settings.json
echo '{"deprecatedCgroupv1": true}' | \
  jq -s '.[0] * .[1]' ~/Library/Group\ Containers/group.com.docker/settings.json - | \
  sponge ~/Library/Group\ Containers/group.com.docker/settings.json
# Restart docker desktop
open --background -a Docker
```
^ copy pasted from: https://github.com/docker/for-mac/issues/6073#issuecomment-1018793677

**Comment by NiftyMist** [comment]
I'm having a similar issue running on Pop!_OS 21.04.  Trying to see if we can migrate our existing molecule testing pipelines from vagrant/virtualbox setups to docker bases methodology.  Using this image I was unable to test a role because it wants to enable a `systemd` service.  But obviously it cannot if `systemd` is not running.  So I decided to create a new virtual environment with fully up to date tools and now I'm getting a completely new error.

# My setup
* `ansible`: 2.12.2
* `molecule`: 3.6.1
* `molecule-docke`r: 1.1.0
* `python`: 3.9.7
* `docker`: 20.10.12
* `OS`: Pop!_OS 21.04

I'm able to create an instance just fine, but when trying to login (with the same `molecule.yml` as above) I get the following error:
```
❯ molecule login
INFO     Running default > login
Traceback (most recent call last):
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/molecule/command/login.py", line 166, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/molecule/command/base.py", line 149, in execute_subcommand
    return command(config).execute()
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/molecule/command/login.py", line 101, in execute
    self._get_login(hostname)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/molecule/command/login.py", line 146, in _get_login
    app.runtime.exec(cmd)
  File "/home/dmitchell/ansible/ansible-latest-virtualenv/lib/python3.9/site-packages/ansible_compat/runtime.py", line 138, in exec
    result = run_func(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env docker exec -e COLUMNS=236 -e LINES=56 -e TERM=bash -e TERM=xterm -ti ubuntu2004 bash'
```

I can manually exec into the container.  `systemd` is still not running.  
```
❯ docker exec -it ubuntu2004 /bin/bash
root@ubuntu2004:/# systemctl show
Failed to connect to bus: No such file or directory
```

**Comment by LorenzoBettini** [comment]
> Fyi, this is an issue between Docker and newer systemd versions (248 and up): [systemd/systemd#19245](https://github.com/systemd/systemd/issues/19245).
> 
> One possible workaround is to boot with the kernel parameter `systemd.unified_cgroup_hierarchy=0`

By booting with that kernel parameter you mean to boot the main OS, right?

**Comment by gomex** [comment]
I am using Docker for Mac and I getting the same error :(

**Comment by FedericoAntoniazzi** [comment]
Hi @gomex, This is a molecule problem, the temporary solution is to just copy that command manually and running it separately.

**Comment by ned300889** [comment]
Hi @gomex, the resolution above is technically true you just need to install the previous version to get this running molecule==3.5.2 works fine. Just uninstall the module then reinstall it with that version number and you're fine.

**Comment by gomex** [comment]
@ned300889 I tried, but I am still getting the same failure. 

I downgraded my Docker for Mac to 4.4.0 and this is working now.

**Comment by geerlingguy** [comment]
I've started getting this too, on latest molecule with latest Docker Desktop for Mac :(

**Comment by ned300889** [comment]
There are two combined issues, molecule issue is mentioned  [here](https://github.com/ansible-community/molecule/issues/3435) and this will be seen throughout providers i believe. 

Docker issue is related to systemd not starting as mentioned [here](https://github.com/docker/for-mac/issues/6073)

I believe a resolution to molecule is pinning the version within the docker build process for now whilst it gets resolved and for the docker issue put a note on the README about a required desktop docker version for MacOS.

**Comment by kozicpetar** [comment]
@NiftyMist yes, you are in the right. My primary problem is running tests on GHA because support containers.

@geerlingguy Jeff, do you have some idea how we can sort this problem ?

**Comment by geerlingguy** [comment]
Related? https://github.com/geerlingguy/docker-debian11-ansible/issues/4

**Comment by abhilashmandaliya** [comment]
> Fyi, this is an issue between Docker and newer systemd versions (248 and up): [systemd/systemd#19245](https://github.com/systemd/systemd/issues/19245).
> 
> One possible workaround is to boot with the kernel parameter `systemd.unified_cgroup_hierarchy=0`

You saved my life :-)

**Comment by kozicpetar** [comment]
I sort problem on my Mac with Docker desktop version `Docker Desktop 4.7.1 (77678)`

I built new container for Ubuntu and Debian without `VOLUME [ "/sys/fs/cgroup" ]`

This is Dockerfile for Ubuntu 20.04:
``` 
FROM ubuntu:focal

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude systemd systemd-sysv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
    /lib/systemd/system/systemd-update-utmp*

RUN systemctl set-default multi-user.target

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
``` 

I do same for Debian 11 and Ubuntu 18.04

My molecule file, you can see there is commented `volumes:`

```
platforms:
  - name: Ubuntu-18.04
    image: docker-ubuntu1804-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    #volumes:
    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: Ubuntu-20.04
    #image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    image: docker-ubuntu2004-ansible:latest
    #command: "/lib/systemd/systemd"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    #volumes:
    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```

After this, all my roles with systemd works as expected.
NOTE: I didn't enable deprecated `"deprecatedCgroupv1": true``

**Comment by MohammadrezaNasrabadi** [comment]
This problem has been occurred for me too.

After two days of troubleshooting, I finally resolve my own issue.

I'm using debian 11 operating system and as docker documentation said, ( this [link](https://docs.docker.com/config/containers/runmetrics/#enumerate-cgroups) from debian 11 to latest cgroup v2 is using.

So I guessed that the problem should be from changing in version of cgroup . Because my co-worker that uses ubuntu 20.04 didn't face such problem.

BTW, after so many tries I decided to mount `/sys` directory to container instead of `/sys/fs/cgroup` in read only type and my problem has been solve.

Hope it will be helpfull for others.

**Comment by d-mankowski-synerise** [comment]
After upgrading AKS to 1.25 (which also upgraded Ubuntu image on K8s nodes from 18.04 to 22.04) we also encountered this issue and neither solution from this thread worked. After some extensive googling and thanks to [this answer](https://serverfault.com/a/1087467/757444) I came up with this:

```Dockerfile
FROM ubuntu:20.04

ENV container docker
STOPSIGNAL SIGRTMIN+3
VOLUME [ "/tmp", "/run", "/run/lock" ]

ARG DEBIAN_FRONTEND=noninteractive

ENV pip_packages "ansible"

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       apt-utils \
       build-essential \
       locales \
       libffi-dev \
       libssl-dev \
       libyaml-dev \
       python3-dev \
       python3-setuptools \
       python3-pip \
       python3-yaml \
       software-properties-common \
       rsyslog systemd systemd-cron sudo iproute2 \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Fix potential UTF-8 errors with ansible-test.
RUN locale-gen en_US.UTF-8

# Install Ansible via Pip.
RUN pip3 install $pip_packages

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Remove unnecessary getty and udev targets that result in high CPU usage when using
# multiple containers with Molecule (https://github.com/ansible/molecule/issues/1104)

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
  /etc/systemd/system/*.wants/* \
  /lib/systemd/system/local-fs.target.wants/* \
  /lib/systemd/system/sockets.target.wants/*udev* \
  /lib/systemd/system/sockets.target.wants/*initctl* \
  /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
  /lib/systemd/system/systemd-update-utmp* \
  /lib/systemd/system/getty.target

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
```

And after build the image, run it like this: `docker run -itd --privileged --cap-add SYS_ADMIN --security-opt seccomp=unconfined --cgroup-parent=docker.slice --cgroupns private --tmpfs /tmp --tmpfs /run --tmpfs /run/lock <image name>`

<img width="545" alt="image" src="https://user-images.githubusercontent.com/101267779/221029198-50b8d843-84cb-454c-b263-3b7acf9b6efa.png">

**Comment by AzraelG** [comment]
I solved the problem changing the volume configuration from /sys/fs/cgroup:/sys/fs/cgroup:ro to /sys/fs/cgroup:/sys/fs/cgroup:rw.

Molecule platform configuration:

`platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true`

**Comment by sirkubax** [comment]
```
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: /lib/systemd/systemd
    volumes:
    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
```
