### ISSUE TITLE
apt install package (molecule testing)

### ISSUE THREAD

**Issue by DarksideVT** [geerlingguy/docker-ubuntu2004-ansible#23]
New to molecule here. So guide me with anything I'm missing, please.

converge.yml
```
- name: Converge
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Include base_install"
      include_role:
        name: "base_install"
```
molecule.yml
```
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-base_install
    image: geerlingguy/docker-ubuntu2004-ansible
    # command: ''
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privilaged: true
    # pre_build_image: true
provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
verifier:
  name: ansible

```

main.yml
```
---
- name: Install nano,htop,snapd
  package:
    name: 
    - nano
    - htop
    - snapd
    state: present
```
error
```
fatal: [molecule-base_install]: FAILED! => {"changed": false, "msg": "No package matching 'nano' is available"}
```

## Expected behavior
APT installs nano, htop, and snapd
